#!/bin/sh
cd ~/statements
for year in 2011 2012 2013 ; do 
	for cust in 47900 58240 43241 ; do
		for month in 01 02 03 04 05 06 07 08 09 10 11 12 ;  do 
			for dy in `cal ${month} ${year}  |grep -v [a-z]` ; do
                                day=`printf "%02d" $dy`
				mkdir -p ~/statements/${year}/${cust}/${month}/${day}
                                for stype in "0770" "0890" "0747" ; do
                                    fname=`echo ~/statements/${year}/${cust}/${month}/${day}/B${cust}R${stype}`
                                    echo "statement ${stype} for customer ${cust} on day ${day}-${month}-${year}" | enscript -t "Statement ${stype}" -o- |ps2pdf -  >${fname}.pdf
                                done
			done 
		done 
	done
done

